name: PR Checks
on: [pull_request]

jobs:
    run_tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: unit_test
              run: |
                  yarn
                  yarn test
              working-directory: ./
    build_code:
        name: Build Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: build
              run: |
                  yarn
                  yarn build
              working-directory: ./
